### PR TITLE
Update circular overlay

### PR DESCRIPTION
**Pull request by JMY1000**
Overlay is now more in keeping with post-Mavericks flattening.

### CODE REVIEW

**Comment by w0lfschild** [comment]
I like the idea, there's just one problem, the icon overlay doesn't go all the way to the edge of the image.

screen shot 2018-01-06 at 11 33 54 pm

**Comment by JMY1000** [comment]
I'm happy to try modify `createIconImage()` as necessary, but unfortunately, I don't understand the build system and thus how to test it, nor fully all the libs you're using. It might be faster for you to do it, though I understand if that's something you're not interested in.

**Comment by w0lfschild** [comment]
I think the issue is that the ring just needs to go all the way to the edge of the of the image without a fade.

**Comment by JMY1000** [comment]
While that would work, that's inconsistent with the rest of the icons. Why not just scale and position the album art to end within the ring?

**Comment by w0lfschild** [comment]
Huh? Here's the result I got with a quick dirty edit of your image using Preview to make the circle go all the way to the edge of the image frame rather than 64px dead space:

screen shot 2018-01-07 at 1 00 47 pm

The only problem is I didn't perfectly get the crop as you can see the fade is a little flat on the bottom.

**Comment by JMY1000** [comment]
Chrome doesn't follow the macOS convention; other apps don't go all the way to the edge. You can see that with this gif.

3o752d0vk2wgvtoiy0

**Comment by w0lfschild** [comment]
Okay thanks, I didn't realize that. I've edited the drawing code a bit.

**Pull request merged**
